"""initial

Revision ID: b13dc738046b
Revises: 
Create Date: 2020-03-18 22:12:10.559838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b13dc738046b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=100), nullable=True),
    sa.Column('create_date', sa.Integer(), nullable=True),
    sa.Column('last_date', sa.Integer(), nullable=True),
    sa.Column('bind_status', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('External_HRapi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('secret', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Goods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('goods_type', sa.String(length=50), nullable=True),
    sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('create_date', sa.Integer(), nullable=True),
    sa.Column('last_date', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Organization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('create_date', sa.Integer(), nullable=True),
    sa.Column('last_date', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['Organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Service_Cluster',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Service_Type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('memo', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Service_level_params',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('tto', sa.Integer(), nullable=True),
    sa.Column('ttr', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('USA_service_contract',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('start_date', sa.Integer(), nullable=True),
    sa.Column('end_date', sa.Integer(), nullable=True),
    sa.Column('memo', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Service_cluster_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('memo', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Service_cluster_id'], ['Service_Cluster.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Service_vendor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('contacts', sa.String(length=50), nullable=True),
    sa.Column('contactus', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=50), nullable=True),
    sa.Column('legal_representative', sa.String(length=50), nullable=True),
    sa.Column('enterprise_code', sa.String(length=50), nullable=True),
    sa.Column('memo', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('service_org', sa.Integer(), nullable=True),
    sa.Column('last_date', sa.Integer(), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['Organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('USA_org',
    sa.Column('USA_service_contract_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['USA_service_contract_id'], ['USA_service_contract.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['Organization.id'], ),
    sa.PrimaryKeyConstraint('USA_service_contract_id', 'org_id')
    )
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('external_hrApi_id', sa.Integer(), nullable=True),
    sa.Column('contacts_id', sa.Integer(), nullable=True),
    sa.Column('wx_session_id', sa.String(length=20), nullable=True),
    sa.Column('wx_open_id', sa.String(length=20), nullable=True),
    sa.Column('create_date', sa.Integer(), nullable=True),
    sa.Column('last_date', sa.Integer(), nullable=True),
    sa.Column('token', sa.String(length=50), nullable=True),
    sa.Column('bind_status', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contacts_id'], ['Contacts.id'], ),
    sa.ForeignKeyConstraint(['external_hrApi_id'], ['External_HRapi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Attachment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('data', sa.LargeBinary(), nullable=True),
    sa.Column('length', sa.Integer(), nullable=True),
    sa.Column('use_num', sa.Integer(), nullable=True),
    sa.Column('create_date', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Service_contract',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('service_vendor_id', sa.Integer(), nullable=True),
    sa.Column('valid_date', sa.Integer(), nullable=True),
    sa.Column('billing_cycle', sa.Integer(), nullable=True),
    sa.Column('billing_cycle_unit', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('memo', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['service_vendor_id'], ['Service_vendor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Service_Item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('contract_id', sa.Integer(), nullable=True),
    sa.Column('service_type_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('memo', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['Service_contract.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['Service.id'], ),
    sa.ForeignKeyConstraint(['service_type_id'], ['Service_Type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Service_contract_attachment',
    sa.Column('service_contract_id', sa.Integer(), nullable=False),
    sa.Column('attachment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['attachment_id'], ['Attachment.id'], ),
    sa.ForeignKeyConstraint(['service_contract_id'], ['Service_contract.id'], ),
    sa.PrimaryKeyConstraint('service_contract_id', 'attachment_id')
    )
    op.create_table('Service_Item_agent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_Item_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('memo', sa.String(length=100), nullable=True),
    sa.Column('create_date', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['service_Item_id'], ['Service_Item.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Service_Item_evaluate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_item_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('highest', sa.Integer(), nullable=True),
    sa.Column('lowest', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['service_item_id'], ['Service_Item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Service_Item_solution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_item_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('memo', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['service_item_id'], ['Service_Item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Service_level_agreemnts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_item_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tto', sa.Integer(), nullable=True),
    sa.Column('ttr', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('last_date', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['service_item_id'], ['Service_Item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('USA_service_item',
    sa.Column('USA_service_contract_id', sa.Integer(), nullable=False),
    sa.Column('service_Item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['USA_service_contract_id'], ['USA_service_contract.id'], ),
    sa.ForeignKeyConstraint(['service_Item_id'], ['Service_Item.id'], ),
    sa.PrimaryKeyConstraint('USA_service_contract_id', 'service_Item_id')
    )
    op.create_table('service_item_goods',
    sa.Column('service_item_id', sa.Integer(), nullable=False),
    sa.Column('goods_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['goods_id'], ['Goods.id'], ),
    sa.ForeignKeyConstraint(['service_item_id'], ['Service_Item.id'], ),
    sa.PrimaryKeyConstraint('service_item_id', 'goods_id')
    )
    op.create_table('Service_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parents_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.Integer(), nullable=True),
    sa.Column('usa_service_item_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('descript', sa.String(length=250), nullable=True),
    sa.Column('scope', sa.Integer(), nullable=True),
    sa.Column('urgency', sa.Integer(), nullable=True),
    sa.Column('workflow_id', sa.String(length=250), nullable=True),
    sa.Column('service_item_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('service_level_agreemnts_id', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('promise_tto', sa.Integer(), nullable=True),
    sa.Column('promise_ttr', sa.Integer(), nullable=True),
    sa.Column('create_date', sa.Integer(), nullable=True),
    sa.Column('accept_date', sa.Integer(), nullable=True),
    sa.Column('assign_date', sa.Integer(), nullable=True),
    sa.Column('resolve_date', sa.Integer(), nullable=True),
    sa.Column('solution_id', sa.Integer(), nullable=True),
    sa.Column('closeing_statment', sa.String(length=250), nullable=True),
    sa.Column('service_status', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['User.id'], ),
    sa.ForeignKeyConstraint(['parents_id'], ['Service_list.id'], ),
    sa.ForeignKeyConstraint(['service_item_id'], ['Service_Item.id'], ),
    sa.ForeignKeyConstraint(['service_level_agreemnts_id'], ['Service_level_agreemnts.id'], ),
    sa.ForeignKeyConstraint(['solution_id'], ['Service_Item_solution.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Service_list_attachment',
    sa.Column('service_list_id', sa.Integer(), nullable=False),
    sa.Column('attachment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['attachment_id'], ['Attachment.id'], ),
    sa.ForeignKeyConstraint(['service_list_id'], ['Service_list.id'], ),
    sa.PrimaryKeyConstraint('service_list_id', 'attachment_id')
    )
    op.create_table('Service_list_contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_list_id', sa.Integer(), nullable=True),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('memo', sa.String(length=100), nullable=True),
    sa.Column('create_date', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['Contacts.id'], ),
    sa.ForeignKeyConstraint(['service_list_id'], ['Service_list.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Service_list_evaluate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_list_id', sa.Integer(), nullable=True),
    sa.Column('service_Item_evaluate_id', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('create_date', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['service_Item_evaluate_id'], ['Service_Item_evaluate.id'], ),
    sa.ForeignKeyConstraint(['service_list_id'], ['Service_list.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Service_list_goods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_list_id', sa.Integer(), nullable=True),
    sa.Column('goods_id', sa.Integer(), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=True),
    sa.Column('create_date', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['goods_id'], ['Goods.id'], ),
    sa.ForeignKeyConstraint(['service_list_id'], ['Service_list.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Service_list_taskList',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_list_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('descript', sa.String(length=250), nullable=True),
    sa.Column('worker_id', sa.Integer(), nullable=True),
    sa.Column('create_date', sa.Integer(), nullable=True),
    sa.Column('response_date', sa.Integer(), nullable=True),
    sa.Column('close_date', sa.Integer(), nullable=True),
    sa.Column('closeing_statment', sa.String(length=250), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['service_list_id'], ['Service_list.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Task_attachment',
    sa.Column('taskList_id', sa.Integer(), nullable=False),
    sa.Column('attachment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['attachment_id'], ['Attachment.id'], ),
    sa.ForeignKeyConstraint(['taskList_id'], ['Service_list_taskList.id'], ),
    sa.PrimaryKeyConstraint('taskList_id', 'attachment_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Task_attachment')
    op.drop_table('Service_list_taskList')
    op.drop_table('Service_list_goods')
    op.drop_table('Service_list_evaluate')
    op.drop_table('Service_list_contact')
    op.drop_table('Service_list_attachment')
    op.drop_table('Service_list')
    op.drop_table('service_item_goods')
    op.drop_table('USA_service_item')
    op.drop_table('Service_level_agreemnts')
    op.drop_table('Service_Item_solution')
    op.drop_table('Service_Item_evaluate')
    op.drop_table('Service_Item_agent')
    op.drop_table('Service_contract_attachment')
    op.drop_table('Service_Item')
    op.drop_table('Service_contract')
    op.drop_table('Attachment')
    op.drop_table('User')
    op.drop_table('USA_org')
    op.drop_table('Service_vendor')
    op.drop_table('Service')
    op.drop_table('USA_service_contract')
    op.drop_table('Service_level_params')
    op.drop_table('Service_Type')
    op.drop_table('Service_Cluster')
    op.drop_table('Organization')
    op.drop_table('Goods')
    op.drop_table('External_HRapi')
    op.drop_table('Contacts')
    # ### end Alembic commands ###
